### ISSUE TITLE
Testing badge mechanism

### ISSUE THREAD

**Issue by mixth** [electinth/constitution#12]

**Comment by Th1nkK1D** [comment]
`staging-banner` created in [electinth/@common](https://electinth.github.io/common/?path=/story/web-components-staging-banner--default)

Please let me know if it's OK. I will test and release the package soon

**Comment by Th1nkK1D** [comment]
Published in electinth@common [v1.2.0](https://github.com/electinth/common/releases/tag/v1.2.0)
Added to constitution in ae7d08be8abea9c673a27828a5d4379794bfb4e0
