### ISSUE TITLE
ทำไมไม่ใช้ HTML ของทางเว็บสำนักงานคณะกรรมการกฤษฎีกา

### ISSUE THREAD

**Issue by wannaphong** [electinth/constitution#8]
ทำไมไม่ใช้ HTML รัฐธรรมนูญของทางเว็บสำนักงานคณะกรรมการกฤษฎีกาครับ ในโพสต์บอกใช้ไฟล์ PDF ทั้งที่ความจริงแล้วมี HTML รัฐธรรมนูญของทางเว็บสำนักงานคณะกรรมการกฤษฎีกา และมีการตรวจสอบรับรอง มาหลายปีแล้วครับ?

**Comment by p16i** [comment]
อาจจะมีปัญหาทางด้านเทคนิคหรือว่า @wannaphong ลองส่งลิงค์แปะเทียบได้ไหมว่า PDF กับ HTML มันต่างกันไหม?

**Comment by wannaphong** [comment]
> 
> 
> อาจจะมีปัญหาทางด้านเทคนิคหรือว่า @wannaphong ลองส่งลิงค์แปะเทียบได้ไหมว่า PDF กับ HTML มันต่างกันไหม?

HTML [https://www.krisdika.go.th/librarian/get?sysid=774606&ext=htm](https://www.krisdika.go.th/librarian/get?sysid=774606&ext=htm) และ PDF [https://www.krisdika.go.th/librarian/get?sysid=774606&ext=pdf](https://www.krisdika.go.th/librarian/get?sysid=774606&ext=pdf)

**Comment by wannaphong** [comment]
พูดคุยกันที่ [https://www.facebook.com/electinth/photos/a.318689725616434/902835617201839](https://www.facebook.com/electinth/photos/a.318689725616434/902835617201839) เรียบร้อยแล้วครับ ขอผิดกระทู้นี้นะครับ
